### ISSUE TITLE
Notification component surpport close callback function

### ISSUE THREAD

**Issue by tirelyl** [NG-ZORRO/ng-zorro-antd#2761] opened 2019-01-10 02:51 UTC
## What problem does this feature solve?
I have a NPS score notification, i want send some info to backend when user close the notification.
## What does the proposed API look like?
options interface add a property
{
  nzOnCancel: () => void
}

**Comment by wendzhue** [comment] 2019-01-10 03:45
Duplicate of #2458

**Comment by wendzhue** [comment] 2019-01-10 03:49
Closing this now. @tirelyl You can track this problem in that issue.

**Closed by wendzhue** 2019-01-10 03:49 UTC
Labels: Component:Notification, 🌈 Feature
