### ISSUE TITLE
Tooltip fails to hide when changing component with component reuse

### ISSUE THREAD

**Issue by prichter98** [NG-ZORRO/ng-zorro-antd#5604] opened 2020-07-23 08:45 UTC
### Reproduction link
[https://stackblitz.com/edit/tooltip-stays-antd](https://stackblitz.com/edit/tooltip-stays-antd)

### Steps to reproduce
1. Have a component that is being reused with a tooltip on a button that navigates to a different component
1. Hover over button to display tooltip
2. Click button

### What is expected?
The page should change and the tooltip should be hidden.

### What is actually happening?
The tooltip stays visible. Also, when scrolling, after clicking the button and before the new component is loaded, the tooltip is no longer being updated and will stay even when moving the mouse away or scrolling.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Chrome, Firefox |

---
I was able to reproduce the same behavior using Angular Material (https://github.com/angular/components/issues/20076), so I assume the Issue is being caused by the overlay cdk.

**Comment by wendellhu95** [comment] 2020-08-13 13:51
Duplicate of #1530. This bug has been there for a long time. It seems that Angular team is not interested in fixing this...

I am closing this now. You can turn to #1530 for temporary solutions. Thank you.

**Closed by wendellhu95** 2020-08-13 13:51 UTC
Labels: Component: Tooltip
