### ISSUE TITLE
modal.create supports the nzData option for injecting component data

### ISSUE THREAD

**Issue by MunMunMiao** [NG-ZORRO/ng-zorro-antd#7827] opened 2023-02-09 05:36 UTC
## What problem does this feature solve?
In the case where nzContent is a component, the create method adds a new nzData option and supports generic passing, allowing strict control over the parameters passed into the component.

## What does the proposed API look like?
api reference at [MatDialog](https://material.angular.io/components/dialog/api#MatDialog)
```ts
import { Component } from '@angular/core'
import { NzModalService, NZ_MODAL_DATA } from 'ng-zorro-antd/modal'

@Component({ template: '<button (click)="open()">open</button>' })
export class MyComponent {
  constructor(private nzModalService: NzModalService) {}

  open(): void{
    this.nzModalService.create<MyModalComponent, ModalData>({
      nzContent: MyModalComponent,
      nzData: {
        text: 'Hello'
      }
    });
  }
}

export interface ModalData {
  text: string;
}

@Component({ template: '<p>{{ data.text }}</p>' })
export class MyModalComponent {
  constructor(@Inject(NZ_MODAL_DATA) public data: ModalData) {}
}
```

**Comment by Nicoss54** [comment] 2023-02-16 16:34
@MunMunMiao your PR is a duplicate of this [one](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7787)

**Comment by MunMunMiao** [comment] 2023-02-17 01:53
> @MunMunMiao thanks for your PR :) But this PR is a duplicate of this [one](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7787)

but. I have some suggestions.

1. It is not recommended to use ```NZ_MODAL_COMPONENT_PARAMS```, you should use ```NZ_DATA```.
2. ModalOptions should be: ```ModalOptions<T = NzSafeAny, D = NzSafeAny, R = NzSafeAny>```

This suggestion is a continuation of the reference with [MatDialog](https://material.angular.io/components/dialog/api#MatDialog),Hope to adopt.

**Comment by Nicoss54** [comment] 2023-02-17 07:51
> > @MunMunMiao thanks for your PR :) But this PR is a duplicate of this [one](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7787)
> 
> I think you still have some problems with your PR. I have some suggestions for you.
> 
> 1. It is not recommended to use `NZ_MODAL_COMPONENT_PARAMS`, you should use `NZ_MODAL_DATA`.
> 2. The generic option for ModalOptions should be: `ModalOptions<T = NzSafeAny, D = NzSafeAny, R = NzSafeAny>`. Because components are mandatory, data and result are optional. So the component should be in the first place. When you don't need result, you can write `this.modal<ModalComponent, ModalData>()`, your current practice needs to write `this.modal<ModalComponent, undefined, ModalData>()`. It does not comply with the first-in, last-out principle.
> 3. The data option for ModalOptions should be: `nzData`, not `nzComponentParams`
> 
> This suggestion is a continuation of the reference with [MatDialog](https://material.angular.io/components/dialog/api#MatDialog).
> 
> When official best practices are available, api naming should use the nomenclature related to the official logic, which reduces the burden on the user's mind, as well as conforming to the community's unified logic. Especially in the official [CdkDialog](https://material.angular.io/cdk/dialog/overview) In the case of.
> 
> Hope to adopt. Thank you.

Hey thanks for your suggestion, i'm totally agree with your two first points :) ! Totally right i didn't follow the naming convention and the first in, last-out principle. It's now integrated ;)

For the third point, since a long time, user of NGZorro use nzComponentParams to pass data to modal component content. If we add a new nzData property as you suggest (and i agree it's the continuation of the reference with MatDialog) and keep nzComponentParams property we will have to way to pass data to our modal component content.

I think it will be a little bit confusing for user don't you think ?

**Comment by MunMunMiao** [comment] 2023-02-17 08:11
> > > @MunMunMiao thanks for your PR :) But this PR is a duplicate of this [one](https://github.com/NG-ZORRO/ng-zorro-antd/pull/7787)
> > 
> > 
> > I think you still have some problems with your PR. I have some suggestions for you.
> > 
> > 1. It is not recommended to use `NZ_MODAL_COMPONENT_PARAMS`, you should use `NZ_MODAL_DATA`.
> > 2. The generic option for ModalOptions should be: `ModalOptions<T = NzSafeAny, D = NzSafeAny, R = NzSafeAny>`. Because components are mandatory, data and result are optional. So the component should be in the first place. When you don't need result, you can write `this.modal<ModalComponent, ModalData>()`, your current practice needs to write `this.modal<ModalComponent, undefined, ModalData>()`. It does not comply with the first-in, last-out principle.
> > 3. The data option for ModalOptions should be: `nzData`, not `nzComponentParams`
> > 
> > This suggestion is a continuation of the reference with [MatDialog](https://material.angular.io/components/dialog/api#MatDialog).
> > When official best practices are available, api naming should use the nomenclature related to the official logic, which reduces the burden on the user's mind, as well as conforming to the community's unified logic. Especially in the official [CdkDialog](https://material.angular.io/cdk/dialog/overview) In the case of.
> > Hope to adopt. Thank you.
> 
> Hey thanks for your suggestion, i'm totally agree with your two first points :) ! Totally right i didn't follow the naming convention and the first in, last-out principle. It's now integrated ;)
> 
> For the third point, since a long time, user of NGZorro use nzComponentParams to pass data to modal component content. If we add a new nzData property as you suggest (and i agree it's the continuation of the reference with MatDialog) and keep nzComponentParams property we will have to way to pass data to our modal component content.
> 
> I think it will be a little bit confusing for user don't you think ?

I think that your PR is "refactor", so don't worry about that.

"nzComponentParams" is fine in the original case. The problem is that if you use "dependency injection" to pass data, then it doesn't apply to "Params" because it's not "Params", it's "Data".

If the "nzComponentParams" option is retained, then users using the set "params" will incorrectly assume that they can use this value directly in the component instead of defining the variable in the constructor first.

In fact, angular officially does the same thing. ng-zorro-antd team actually made a bad choice to use "nzComponentParams" because this option would mess up, for example:

1. incorrectly passing "private" variables.
2. Unintentionally modifying some internal variables of the component.
3. Exposing some internal variables to "nzComponentParams".

I think we should fix this wrong use case now. what do you think?

**Comment by Nicoss54** [comment] 2023-02-17 10:32
> 

Yes it was a fast refactor to remove the depracted way, if we remove the nzComponentParams i am totally agree with you :). Unfortunatly i am not able to take such decision without the approval of a maintainer

@simplejason  are you agree to remove the nzComponentParams property for the next major version, if you are agree i will made the necessary developpement.

Is it also okey for you @MunMunMiao ?

**Comment by MunMunMiao** [comment] 2023-02-17 10:36
> > 
> 
> 
> 
> Yes it was a fast refactor to remove the depracted way, if we remove the nzComponentParams i am totally agree with you :). Unfortunatly i am not able to take such decision without the approval of a maintainer
> 
> 
> 
> @simplejason  are you agree to remove the nzComponentParams property for the next major version, if you are agree i will made the necessary developpement.
> 
> 
> 
> Is it also okey for you @MunMunMiao ?

OK. Hope to get permission.

**Comment by simplejason** [comment] 2023-02-17 10:50
> > > 
> > 
> > 
> > Yes it was a fast refactor to remove the depracted way, if we remove the nzComponentParams i am totally agree with you :). Unfortunatly i am not able to take such decision without the approval of a maintainer
> > @simplejason  are you agree to remove the nzComponentParams property for the next major version, if you are agree i will made the necessary developpement.
> > Is it also okey for you @MunMunMiao ?
> 
> OK. Hope to get permission.

I need to check the context, marking a property as deprecated tries to ensure compatibility in the current major release(v15.x) is better(if we can promise), feel free to refactor the component if you confirm it's correct to deprecate `nzComponentParams` :) Please check this PR  if you @Nicoss54 @hsuanxyz @yangjunhan have time to do that.

**Comment by Nicoss54** [comment] 2023-02-17 11:18
> > > Yes it was a fast refactor to remove the depracted way, if we remove the nzComponentParams i am totally agree with you :). Unfortunatly i am not able to take such decision without the approval of a maintainer
> > > @simplejason  are you agree to remove the nzComponentParams property for the next major version, if you are agree i will made the necessary developpement.
> > > Is it also okey for you @MunMunMiao ?
> > 
> > 
> > OK. Hope to get permission.
> 
> I need to check the context, marking a property as deprecated tries to ensure compatibility in the current major release(v15.x) is better(if we can promise), feel free to refactor the component if you confirm it's correct to deprecate `nzComponentParams` :) Please check this PR if you @Nicoss54 @hsuanxyz @yangjunhan have time to do that.

Okey cool, so I'll will take this development ;)

Thanks for your fast answer @simplejason

**Comment by MunMunMiao** [comment] 2023-02-17 11:39
> > > > Yes it was a fast refactor to remove the depracted way, if we remove the nzComponentParams i am totally agree with you :). Unfortunatly i am not able to take such decision without the approval of a maintainer
> 
> > > > @simplejason  are you agree to remove the nzComponentParams property for the next major version, if you are agree i will made the necessary developpement.
> 
> > > > Is it also okey for you @MunMunMiao ?
> 
> > > 
> 
> > > 
> 
> > > OK. Hope to get permission.
> 
> > 
> 
> > I need to check the context, marking a property as deprecated tries to ensure compatibility in the current major release(v15.x) is better(if we can promise), feel free to refactor the component if you confirm it's correct to deprecate `nzComponentParams` :) Please check this PR if you @Nicoss54 @hsuanxyz @yangjunhan have time to do that.
> 
> 
> 
> Okey cool, so I'll will take this development ;)
> 
> 
> 
> Thanks for your fast answer @simplejason 

thank you for your help.  I close the PR.

**Closed** 2023-02-17 11:39 UTC
Labels: Component: Modal

**Comment by HyperLife1119** [comment] 2023-04-10 03:30
A new [`ComponentRef#setInput`](https://angular.io/api/core/ComponentRef#setInput) API has been added in Angular v14, through which data can be passed to dynamic components, and which can strictly control the parameters passed to components.

I think we should rethink:

1. Should we really deprecate `nzComponentParams`?
2. Is it still best practice to pass data to dynamic components via dependency injection when there is a `ComponentRef#setInput` API?

**Comment by MunMunMiao** [comment] 2023-04-10 03:35
> A new [`ComponentRef#setInput`](https://angular.io/api/core/ComponentRef#setInput) API has been added in Angular v14, through which data can be passed to dynamic components, and which can strictly control the parameters passed to components.
> 
> I think we should rethink:
> 
> 1. Should we really deprecate `nzComponentParams`?
> 2. Is it still best practice to pass data to dynamic components via dependency injection when there is a `ComponentRef#setInput` API?

When use create, `nzComponentParams` does not have good type support. you can write down your design ideas.

**Comment by HyperLife1119** [comment] 2023-04-10 04:42
When `nzContent` is a component, the component is not necessarily only used for `nzModel`, it may also be used in templates, and it may also come from a third-party library without `NZ_MODAL_DATA`.
When writing this component, it should be decoupled from `nzModel`, that is to say, it does not need `NZ_MODAL_DATA`.
At present, the main advantage of using `NZ_MODAL_DATA` is to bring better type support, and the disadvantage is that it will increase coupling.

I think `nzComponentParams` should be kept instead of deprecated, and `nzComponentParams` should be migrated to `ComponentRef#setInput` API.

If agreed, I will submit a PR for this.

**Comment by MunMunMiao** [comment] 2023-04-10 04:54
I understand what you mean now.

However, in the projects I have worked on, using a third-party dialog may not be a best practice as they are often uncontrollable.

The best practice should be to create a dialog that references third-party components and defines interfaces `DialogData ` and `DialogResult` in the dialog

**Comment by HyperLife1119** [comment] 2023-04-10 05:03
Sounds good, I agree with you now 😄.

**Comment by MunMunMiao** [comment] 2023-04-10 05:04
> Sounds good, I agree with you now 😄.

I think we need to limit users to a certain range in order to improve the quality of the entire project.👍

**Comment by Nicoss54** [comment] 2023-07-18 15:28
> > @MunMunMiao @Nicoss54 After upgrading to 16.1.0, we noticed that Input parameters are not set anymore when opened via the ModalService. After reading the conversation, I understand why it was decided to move away and use nzData, even though this was not very clear from the change logs :-)
> > Also while this approach is cleaner, isn't it limiting how a component is opened/used? Indeed we now have to write the component knowing that it will be opened within a Modal. Before, we could easily switch from a modal to a drawer and vice versa, or even use the component in another one using Inputs parameters.
> 
> You can refer to: [#7827 (comment)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7827#issuecomment-1501389206)
> 
> > Does that mean that for such cases, the component should now implement both input and support data injection? and handle the assignment logic from data to the input parameters? Or did I miss something?
> > One more question. Is it planned to also take the same approach for the DrawerService and its nzContentParams?
> 
> In the future, I will submit a PR to remove nzContentParams from DrawerService. @Nicoss54 what do you think?

Hi everyone :). Of course for the same reason of modalService it will be a good idea to change the behavior of DrawerService and to be honest I am working on it :) @MunMunMiao This PR will appear coming soon. 

As for modalService I think it will be a good idea to deprecated the nzContentParams first with maybe a better communication of this deprecation and the totally remove it 

@simplejason @MunMunMiao do you think it’s a good idea ?

**Comment by MunMunMiao** [comment] 2023-07-18 19:11
> Thank you @MunMunMiao I saw the comment but I guess that I did not digest properly the info ;-)
> 
> So the idea is to wrap the component inside another one to handle the data exchange.
> 
> Looking forward to see the PR @Nicoss54 is preparing for the DrawerService. I suspect that the injection token will be different than for modal, which will mean creating multiple wrappers for different purposes…a bit more work for those like us but this looks cleaner at the end.

you can see my example https://stackblitz-starters-f82ymy.stackblitz.io

**Comment by silviu-laudacescu** [comment] 2023-12-20 23:56
I have changed with nzData, I am not sure if thats the reason but now my modals are not opening. ng-zorro-antd 16.2.0 version and angular 16.2.10. Does somebody have an idea why?

**Comment by Nicoss54** [comment] 2023-12-21 06:54
> I have changed with nzData, I am not sure if thats the reason but now my modals are not opening. ng-zorro-antd 16.2.0 version and angular 16.2.10. Does somebody have an idea why?

Without a reproduction link or an error message it will quite complicated to help.

**Comment by silviu-laudacescu** [comment] 2023-12-21 08:43
No errors when I click to open modal.
after upgrade to angular 16 I had this issue: 
Error: export 'NzMenuItemDirective' (imported as 'i4$1') was not found in 'ng-zorro-antd/menu' (possible exports: MenuDropDownTokenFactory, MenuGroupFactory, MenuService, MenuServiceFactory, NzIsMenuInsideDropDownToken, NzMenuDirective, NzMenuDividerDirective, NzMenuGroupComponent, NzMenuItemComponent, NzMenuModule, NzMenuServiceLocalToken, NzSubMenuComponent, NzSubMenuTitleComponent, NzSubmenuInlineChildComponent, NzSubmenuNoneInlineChildComponent, NzSubmenuService)
but I reinstalled a few times ng-zorro-antd different versions, and now it doesn't show.

**Comment by Nicoss54** [comment] 2023-12-21 08:46
> No errors when I click to open modal.
> 
> after upgrade to angular 16 I had this issue:
> 
> _Error: export 'NzMenuItemDirective' (imported as 'i4$1') was not found in 'ng-zorro-antd/menu' (possible exports: MenuDropDownTokenFactory, MenuGroupFactory, MenuService, MenuServiceFactory, NzIsMenuInsideDropDownToken, NzMenuDirective, NzMenuDividerDirective, NzMenuGroupComponent, NzMenuItemComponent, NzMenuModule, NzMenuServiceLocalToken, NzSubMenuComponent, NzSubMenuTitleComponent, NzSubmenuInlineChildComponent, NzSubmenuNoneInlineChildComponent, NzSubmenuService)_
> 
> but I reinstalled a few times ng-zorro-antd different versions, and now it doesn't show.

Did you try to reinstall all your dependencies. Because the change of nzData have no relation with this error

**Comment by silviu-laudacescu** [comment] 2023-12-21 08:49
yes

**Comment by gan0928** [comment] 2023-12-29 03:17
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/19318827/849cafad-34ac-4a22-8c97-4231cf61df15)
![image](https://github.com/NG-ZORRO/ng-zorro-antd/assets/19318827/5f28f1d4-d028-4906-ae2b-396a9dd0ac68)

same here any solution ? 

Try delete node module , reinstall. 
Clear cache 

all not working.

**Comment by Nicoss54** [comment] 2023-12-29 13:10
> ![image](https://private-user-images.githubusercontent.com/19318827/293304143-849cafad-34ac-4a22-8c97-4231cf61df15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTU1NzEsIm5iZiI6MTcwMzg1NTI3MSwicGF0aCI6Ii8xOTMxODgyNy8yOTMzMDQxNDMtODQ5Y2FmYWQtMzRhYy00YTIyLThjOTctNDIzMWNmNjFkZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEzMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNjk5YWRhODkzOWNlYzY5OWY4ZTM5MTBiMjJjNGIwYTJjYWU4NjZlOWIxZjhlZTNkNTAwOTQ1ZjZjN2U0MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.76i7wbzcvXzsIcwzi8zaKIKIe_bRVSbasQB38YsZxrI) ![image](https://private-user-images.githubusercontent.com/19318827/293304222-5f28f1d4-d028-4906-ae2b-396a9dd0ac68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NTU1NzEsIm5iZiI6MTcwMzg1NTI3MSwicGF0aCI6Ii8xOTMxODgyNy8yOTMzMDQyMjItNWYyOGYxZDQtZDAyOC00OTA2LWFlMmItMzk2YTlkZDBhYzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDEzMDc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTc0MDY5Njk4NWU3YzI0MjJkNDUxNDQzNTQxYmQzZWQzOGVkNWNiMTdiM2ZmMzk3YTYzYTg4ZGEwYjM5NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bruAOX-bQh81d4y8ZlPtrkcvN1sWaKwRZx-xy8WzMRI)
> 
> same here any solution ?
> 
> Try delete node module , reinstall. Clear cache
> 
> all not working.

Hello hello :) the error here is not an error due to the modal component. You import NzMenuItenDirective which is not correct. It’s NzMenuItemComponent or NzMenuDirective. But the ng zorro library don’t export NzMenuItemDirective, that why in the error you have the suggestion of NzMenuDirective. 

Happy coding

**Comment by silviu-laudacescu** [comment] 2024-01-01 11:22
> > I have changed with nzData, I am not sure if thats the reason but now my modals are not opening. ng-zorro-antd 16.2.0 version and angular 16.2.10. Does somebody have an idea why?
> 
> Without a reproduction link or an error message it will quite complicated to help.

found fix but I need to do that for all the modals. I need to wrap all the content form the <nz-Modal> in a ng-container.
 Can I fix this issue without change this in all modals?

**Comment by whittssg** [comment] 2024-03-06 17:48
Maybe I missed something in this thread but how do you use a component that is setup as in this thread but not in a modal. I added the following to my components and used nzData in the create modal function (which works fine when the component is used in a modal:

public data = inject<IModalData>(NZ_MODAL_DATA);

or

constructor(@Inject(NZ_MODAL_DATA) public data: IModalData


Before i upgraded I was using the same component in a modal and in other places but now with this added i get this error when using the component anywhere other than with a modal:

ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionToken NZ_MODAL_DATA -> InjectionToken NZ_MODAL_DATA]: 

Thanks,

**Comment by MunMunMiao** [comment] 2024-03-06 18:59
> Maybe I missed something in this thread but how do you use a component that is setup as in this thread but not in a modal. I added the following to my components and used nzData in the create modal function (which works fine when the component is used in a modal:
> 
> public data = inject(NZ_MODAL_DATA);
> 
> or
> 
> constructor(@Inject(NZ_MODAL_DATA) public data: IModalData
> 
> Before i upgraded I was using the same component in a modal and in other places but now with this added i get this error when using the component anywhere other than with a modal:
> 
> ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionToken NZ_MODAL_DATA -> InjectionToken NZ_MODAL_DATA]:
> 
> Thanks,

Can you provide a minimum replication instance?

**Comment by Nicoss54** [comment] 2024-03-08 14:36
> Maybe I missed something in this thread but how do you use a component that is setup as in this thread but not in a modal. I added the following to my components and used nzData in the create modal function (which works fine when the component is used in a modal:
> 
> public data = inject(NZ_MODAL_DATA);
> 
> or
> 
> constructor(@Inject(NZ_MODAL_DATA) public data: IModalData
> 
> Before i upgraded I was using the same component in a modal and in other places but now with this added i get this error when using the component anywhere other than with a modal:
> 
> ERROR NullInjectorError: R3InjectorError(AppModule)[InjectionToken NZ_MODAL_DATA -> InjectionToken NZ_MODAL_DATA]:
> 
> Thanks,

Hello :) sorry for the late answer! So if I understand well the problem, you use a share component that can be displayed both in a modal and in a page. 

So that normal if you have this injector error outside the modal because the provider NZ_MODAL_DATA is instanciate and injected in the modal component, thanks to how is solved a dependency injection, your custom component have access to the parent injector (here the modal container component which have the NZ_MODAL_DATA) 

if you want to use your component you have to use the @Optional decorator to make the dependency injection optional, and don’t have this error anymore and pass the data with Input (data which I suppose is the same of nzData)

**Comment by whittssg** [comment] 2024-03-08 15:17
@Nicoss54 Thanks alot, the @optional worked perfectly.
