### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by zhanglong19891129** [NG-ZORRO/ng-zorro-antd#70] opened 2017-08-17 10:06 UTC
C:\Users\admin>cd mydemo

C:\Users\admin\mydemo>ng serve --port 9080 --open
** NG Live Development Server is listening on localhost:9080, open your browser on http://localhost:9080 **
 19% building modules 77/97 modules 20 active ...re-js\modules\_array-from-iterable.jswebpack: wait until bundle finished: /                              Date: 2017-08-17T10:02:43.570Z
Hash: d456f32e1ed94ac2996a
Time: 13270ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 23.1 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 210 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.6 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 5.58 MB [initial] [rendered]

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in C:/Users/admin/mydemo/node_modules/ng-zorro-antd/node_modules/@angular/core/core.d.ts, resolving symbol NgZorroAntdModule in C:/Users/admin/mydemo/node_modules/ng-zorro-antd/src/release/ng-zorro-antd.module.d.ts, resolving symbol NgZorroAntdModule in C:/Users/admin/mydemo/node_modules/ng-zorro-antd/src/release/ng-zorro-antd.module.d.ts

webpack: Failed to compile.

**Comment by trotyl** [comment] 2017-08-17 10:07
Duplicate of https://github.com/NG-ZORRO/ng-zorro-antd/issues/23.

**Closed** 2017-08-19 05:12 UTC
