### ISSUE TITLE
Collapse折叠面板-Safari 12.1 浏览器下无法折叠后再展开

### ISSUE THREAD

**Issue by Credo-Zhao** [NG-ZORRO/ng-zorro-antd#3205] opened 2019-04-02 02:53 UTC
### Reproduction link
[https://marmri.run.stackblitz.io](https://marmri.run.stackblitz.io)

### stackblitz不用看
copy的官网的.直接官网测试就能复现.

### Steps to reproduce
Collapse折叠面板-Safari 12.1 浏览器下无法折叠后再展开
Safari 12.1 浏览器下官网测试即可.

### What is expected?
可正常展开,叠起.

### What is actually happening?
可正常展开,叠起.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.2.0 |
| Browser | Safari 12.1 |

**Comment by wendzhue** [comment] 2019-04-02 04:44
Duplicate of #3098

**Closed by wendzhue** 2019-04-02 04:44 UTC
