### ISSUE TITLE
date-pickerIE兼容问题

### ISSUE THREAD

**Issue by jikedenaonao** [NG-ZORRO/ng-zorro-antd#5889] opened 2020-10-10 03:18 UTC
### Reproduction link
[https://codesandbox.io](https://codesandbox.io)

### Steps to reproduce
https://ng.ant.design/version/9.3.x/components/date-picker/zh

### What is expected?
ie不会自动触发时间选择浮动框

### What is actually happening?
ie自动触发时间选择浮动框

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | IE |

**Comment by wenqi73** [comment] 2020-10-10 04:14
Duplicate of #5562. 10.0.1 已修复

**Closed by wenqi73** 2020-10-10 04:14 UTC
Labels: Component: DatePicker
