### ISSUE TITLE
Site doesn't work correctly 

### ISSUE THREAD

**Issue by AnanichEgor** [NG-ZORRO/ng-zorro-antd#8523] opened 2024-04-23 20:37 UTC
### Reproduction link
[https://stackblitz.com/run?file=src%2Fstyles.css,src%2Fapp%2Fapp.component.ts](https://stackblitz.com/run?file=src%2Fstyles.css,src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
1) open site https://ng.ant.design/
2) try to open next pages:

- components -> Select
- components -> Dropdown
- components -> Tooltip
... a lot of places 

3) open console in any page

Error in console:

chunk-NOKK6CHT.js:7 ERROR TypeError: t.hasAttribute is not a function
    at u7 (chunk-NOKK6CHT.js:7:28447)
    at FC (chunk-NOKK6CHT.js:7:48131)
    at RC (chunk-NOKK6CHT.js:7:48094)
    at NC (chunk-NOKK6CHT.js:7:48071)
    at Mo.create (chunk-NOKK6CHT.js:7:70206)
    at bf.createComponent (chunk-NOKK6CHT.js:7:73895)
    at new e (chunk-NOKK6CHT.js:13:247232)
    at e.ɵfac [as factory] (chunk-NOKK6CHT.js:13:247459)
    at fr (chunk-NOKK6CHT.js:7:23904)
    at WC (chunk-NOKK6CHT.js:7:51361)

4) Scripts on pages do not work.

### What is expected?
- No errors in console.
- Scripts on pages do work.

### What is actually happening?
https://ng.ant.design/
Error in console.
Scripts on pages do not work.

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.4.0 |
| Browser | chrome |

**Comment by AnanichEgor** [comment] 2024-04-23 20:38
<img width="859" alt="image" src="https://github.com/NG-ZORRO/ng-zorro-antd/assets/47529200/dab15828-593f-4ed4-a48d-49294e084ea5">

**Comment by vmmartinezlona** [comment] 2024-04-24 17:45
It's not resolved. 
I can't see the code examples of many components, and the error in the console didn't dissapear :(

**Comment by maev-mcbo** [comment] 2024-04-25 12:44
none of the code block cant be toggle.

**Comment by canadakickass** [comment] 2024-04-26 23:36
same here. cannot open code blocks and many other things

**Comment by RabbiIslamRony** [comment] 2024-04-28 02:45
@ng-zorro-bot The site https://ng.ant.design/ is experiencing persistent script errors, impairing its functionality across multiple pages. Despite the passage of considerable time, the support team has not addressed this critical issue. This lack of responsiveness is highly unsatisfactory, underscoring the importance of promptly diagnosing and resolving the root cause of the site's malfunction

**Closed** 2024-04-29 02:38 UTC
