### ISSUE TITLE
Layout issue on NzTableComponent when using nzCustomFilter and nzShowSort at the same time

### ISSUE THREAD

**Issue by worki2k1** [NG-ZORRO/ng-zorro-antd#3723] opened 2019-07-03 09:21 UTC
### Reproduction link
[https://stackblitz.com/edit/angular-t4z2kr](https://stackblitz.com/edit/angular-t4z2kr)

### Steps to reproduce
Add `nzShowSort` and `nzCustomFilter` to a `<th>` at the same time.

### What is expected?
The search-icon should be placed on the right edge of the column header.

### What is actually happening?
The search-icon is placed between title and sorting arrow icons.

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.0.1 |
| Browser | Firefox Developer Edition 69.0a2 |

---
This sample is based on "Customized filter panel" demo in documentation

**Comment by vthinkxie** [comment] 2019-07-03 09:37
duplicate of #3721

**Closed by vthinkxie** 2019-07-03 09:37 UTC
Labels: Component: Layout
