### ISSUE TITLE
There is no open/close method for NzDatePickerComponent

### ISSUE THREAD

**Issue by chandrakantnaik789** [NG-ZORRO/ng-zorro-antd#5251] opened 2020-05-11 06:53 UTC
## What problem does this feature solve?
I want an open/close method for opening or closing of DatePicker
There is open/close method for NzTimePickerComponent which is really handy to open close time picker dynamically from component
## What does the proposed API look like?
open(): open date picker
close(): close date picker

**Comment by wenqi73** [comment] 2020-09-14 12:06
Duplicate of #3352

**Closed by wenqi73** 2020-09-14 12:06 UTC
Labels: Component: DatePicker, 🌈 Feature Request
