### ISSUE TITLE
Jalali (Persian) datepicker support

### ISSUE THREAD

**Issue by phoneticem** [NG-ZORRO/ng-zorro-antd#6341] opened 2021-01-12 20:31 UTC
## What problem does this feature solve?
I need to use ng zorro datepicker as Jalali (Persian), I searched anything but I got no result, if you don't have free time to implement the feature please provide me a document about Ng zorro date picker to help me to implement it ASAP, thank you

## What does the proposed API look like?
<ng-date-picker-fa></ng-date-picker-fa>

**Comment by wenqi73** [comment] 2021-01-13 02:31
Duplicate of #6270.

**Closed** 2021-01-13 02:32 UTC
Labels: Component: DatePicker

**Comment by saeidi-dev** [comment] 2022-01-30 05:52
The date picker problem is not resolved. Please help if possible

**Comment by Abbasr7** [comment] 2024-11-18 11:09
Hello everyone, I recently released a datepicker that supports the Jalali calendar and has good features, you can use it.

https://www.npmjs.com/package/@qeydar/datepicker

![image](https://github.com/user-attachments/assets/e854fa58-cb9d-4666-80bf-276988ea0a5a)
