### ISSUE TITLE
NzNotificationService hmr模式出错

### ISSUE THREAD

**Issue by Anberm** [NG-ZORRO/ng-zorro-antd#3915] opened 2019-08-02 15:36 UTC
### Reproduction link
[https://stackblitz.com/edit/angular-arznwf?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-arznwf?file=src/app/app.component.ts)

### Steps to reproduce
1.点击各个按钮，运行正常
2.修改代码，保存，触发热更新
3.点击按钮，运行错误
![notify](https://user-images.githubusercontent.com/34148806/62381530-48005980-b57e-11e9-99a7-00232d448e0b.gif)

### What is expected?
正常弹出提示信息

### What is actually happening?
ViewDestroyedError: Attempt to use a destroyed view: detectChanges

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.1.2 |
| Browser | 75.0.3770.80（正式版本） （64 位） |

**Comment by wendzhue** [comment] 2019-08-02 16:10
Duplicate of #3845.

**Closed by wendzhue** 2019-08-02 16:10 UTC
Labels: Component: Notification
