### ISSUE TITLE
modal中的table无数据empty不居中

### ISSUE THREAD

**Issue by gas0324** [NG-ZORRO/ng-zorro-antd#5746] opened 2020-09-07 03:52 UTC
### Reproduction link
[https://stackblitz.com/edit/angular-cpjggz?file=package.json](https://stackblitz.com/edit/angular-cpjggz?file=package.json)

### Steps to reproduce
1.modal中添加table
2.table设置 nzScroll

### What is expected?
empty不居中

### What is actually happening?
设置为empty居中

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | chrome |

**Comment by wenqi73** [comment] 2020-09-13 14:52
Duplicate of #5526.

**Closed by wenqi73** 2020-09-13 14:52 UTC
