### ISSUE TITLE
popover: ERROR in Cannot combine @Input decorators with query decorators

### ISSUE THREAD

**Issue by TxOne** [NG-ZORRO/ng-zorro-antd#4109] opened 2019-09-03 06:38 UTC
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-qajbga](https://stackblitz.com/edit/ng-zorro-antd-start-qajbga)

### Steps to reproduce
ng-zorro-antd/components/popover/nz-popover.component.ts

### What is expected?
https://angular.io/guide/deprecations#contentchild--input-used-together

@Input()  xxx: NzTSType;
@ContentChild('neverUsedTemplate' { static: true }) xxxx: NzTSType;

### What is actually happening?
 @Input() @ContentChild('neverUsedTemplate', { static: true }) nzTitle: NzTSType;
 @Input() @ContentChild('nzTemplate', { static: true }) nzContent: NzTSType;

  ERROR in Cannot combine @Input decorators with query decorators

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.2.1 |
| Browser | Chrome 75 |

---
angular 8.0  开启 lvy  会报错。

**Comment by wendzhue** [comment] 2019-09-03 07:06
Duplicate of #3682.

**Comment by wendzhue** [comment] 2019-09-03 07:06
Track #4042.

**Closed by wendzhue** 2019-09-03 07:06 UTC
Labels: Component: Input
