### ISSUE TITLE
IconService constructor missing arguments

### ISSUE THREAD

**Issue by KhaledSMQ** [NG-ZORRO/ng-zorro-antd#2719] opened 2018-12-30 09:04 UTC
missing DomSanitizer arguments in 
 
https://github.com/NG-ZORRO/ng-zorro-antd/blob/6554cf51ccbce08c755b0a3b8a9e968771c3113d/components/icon/nz-icon.service.ts#L143
  
```
protected sanitizer: DomSanitizer
```
https://github.com/ant-design/ant-design-icons/blob/39d709f11e47f8a9c32ba2449f8f7df09f77f959/packages/icons-angular/lib/component/icon.service.ts#L64

**Comment by wendzhue** [comment] 2018-12-30 15:11
Duplicate of #2721

**Closed by wendzhue** 2018-12-30 15:11 UTC
Labels: type:invalid
