### ISSUE TITLE
nzTreeNodePadding does not work in tree-view component

### ISSUE THREAD

**Issue by xia930425** [NG-ZORRO/ng-zorro-antd#8430] opened 2024-03-11 07:15 UTC
### Reproduction link
[https://stackblitz.com/edit/angular-l8dlqv?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-l8dlqv?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
Using nzTreeNodePadding, expand the parent to find that the child is aligned with the parent, with no padding-left in the style

### What is expected?
Using nzTreeNodePadding, children are indented after the parent level is expanded

### What is actually happening?
With nzTreeNodePadding, children are not indented after the parent level is expanded

| Environment | Info |
|---|---|
| ng-zorro-antd | 17.2.0 |
| Browser | Chrome 122.0.6261.112 |

**Comment by ParsaArvanehPA** [comment] 2024-03-11 13:25
Hi @xia930425 
Your reproduction link is broken, can you provide another one?

**Comment by xia930425** [comment] 2024-03-12 00:49
> Hi @xia930425 Your reproduction link is broken, can you provide another one?

Link has been updated https://stackblitz.com/edit/angular-l8dlqv?file=src%2Fapp%2Fapp.component.ts

**Comment by altso** [comment] 2024-03-13 14:40
The bug makes Tree unusable. Can this be prioritized, please?

**Comment by altso** [comment] 2024-03-13 15:12
Actually, it looks like it's fixed in the latest `17.3.0` https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

**Comment by ParsaArvanehPA** [comment] 2024-03-14 09:20
> Actually, it looks like it's fixed in the latest `17.3.0` https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

@xia930425 
Could you confirm that upgrading to version `17.3.0` fixes your problem or not?

**Comment by ParsaArvanehPA** [comment] 2024-03-14 14:50
I checked the Op's stackblitz, but I could'nt generate the same bug on my local machine. 
This is the sample repo I made for this bug([link](https://github.com/ParsaArvanehPA/tree-view-sample)), as you can see the Tree component is working fine.

I got some errors while trying to serve the original post's stackblitz, for example there are some dependencies that are for angular version 11, and there is no `serve` command configured in the `angular.json` file, so I can not really debug the OP's example on my local machine and copying the provided code into another angular project works fine for me; if anyone reading this message has the same problem, please provide a buildable sample and link it in the comment section 🙏

**Comment by xia930425** [comment] 2024-03-18 02:31
@ParsaArvanehPA ，No abnormalities were found after upgrading to version 17.3.0. After multiple tests, it was confirmed that the abnormalities only appeared in version 17.2.0.

**Closed** 2024-03-21 01:50 UTC
Labels: Component: TreeView
