### ISSUE TITLE
InputNumber数字输入框 13.3.1 更新后控制台报错

### ISSUE THREAD

**Issue by 232650413** [NG-ZORRO/ng-zorro-antd#7525] opened 2022-06-20 06:59 UTC
### Reproduction link
[https://r8d1td--run.stackblitz.io](https://r8d1td--run.stackblitz.io)

### Steps to reproduce
InputNumber数字输入框 13.3.1 更新后控制台报错 ERROR ReferenceError: Cannot access 'NzInputNumberComponent' before initialization

### What is expected?
处理报错

### What is actually happening?
InputNumber数字输入框 13.3.1 更新后控制台报错 ERROR ReferenceError: Cannot access 'NzInputNumberComponent' before initialization

| Environment | Info |
|---|---|
| ng-zorro-antd | 13.3.1 |
| Browser | chrome |

**Comment by haeck98** [comment] 2022-06-20 07:09
I get the same error on v13.3.1. It happens in build file `node_modules/ng-zorro-antd/fesm2015/ng-zorro-antd-input-number.mjs:345` where the call to `i0.ɵɵngDeclareClassMetadata(...)` accesses `NzInputNumberComponent` as an argument, before the class itself is defined. Removing the line referencing `NzInputNumberComponent` resolves the issue.

**Comment by haeck98** [comment] 2022-06-20 07:13
Note: On version 13.2.2 the class `NzInputNumberComponent` is defined right at the start of the file, which is not the case for version 13.3.1.

**Comment by zhaowenping001** [comment] 2022-06-20 07:47
I also encountered this problem when building my project with ng-alain
resolve
Use low version --> "ng-zorro-antd": "13.1.1"

**Comment by huajian123** [comment] 2022-06-21 07:38
我更改了package-lock.json，解决了这个问题
https://github.com/huajian123/ng-ant-admin/blob/master/package-lock.json
可以尝试一下

**Comment by lengsehuoyan** [comment] 2022-06-21 15:29
我也遇到了同样的问题。

**Comment by 232650413** [comment] 2022-06-24 02:42
> `npm install ng-zorro-antd@13.1.1 `可

🤣

**Comment by simplejason** [comment] 2022-06-24 13:16
We are investigating the cause and will fix it as soon as possible

**Comment by simplejason** [comment] 2022-06-25 13:39
> We are investigating the cause and will fix it as soon as possible. For now you can set the version ng-zorro-antd to be `13.2.x` or `13.1.x`

This bug is fixed in the version `13.3.2`, you can exceute `npm install ng-zorro-antd@13.3.2` to try again :)

**Closed by simplejason** 2022-06-25 13:39 UTC
Labels: Component: Input
