### ISSUE TITLE
Optimizing: Can modal components provide drag-and-drop functionality

### ISSUE THREAD

**Issue by answercxy** [NG-ZORRO/ng-zorro-antd#3752] opened 2019-07-09 01:29 UTC
## What problem does this feature solve?
Experience optimization

## What does the proposed API look like?
I hope the API is configurable, like nzTitle, nzVisible

**Comment by wendzhue** [comment] 2019-09-23 09:17
Duplicate of #2075.

**Closed** 2019-09-23 09:18 UTC
Labels: Component: Modal
