### ISSUE TITLE
内嵌菜单折叠功能异常

### ISSUE THREAD

**Issue by awmleer** [NG-ZORRO/ng-zorro-antd#607] opened 2017-11-24 09:36 UTC
## Version

0.6.0

## Environment

直接打开即可

## Reproduction link

[https://ng.ant.design/#/components/menu](https://ng.ant.design/#/components/menu)

## Steps to reproduce

1. 找到代码演示里的内嵌菜单
2. 点击Navigation Two将其展开
3. 点击Submenu将其展开
4. 再点击Navigation Two将其收起
5. 再次点击Navigation Two将其展开
6. 此时点击Submenu会发现并不能将其正常收起，再点击一下的话会看到展开动画

## What is expected?

上述步骤中的6应该是：点击Submenu应该可以正常收起

## What is actually happening?

上述步骤中的6未能正常收起Submenu

**Comment by vthinkxie** [comment] 2017-11-25 11:39
it is a strange bug that caused by animation, it will be ok if remove this line https://github.com/NG-ZORRO/ng-zorro-antd/blob/37cef47ac8c033a5dcc104a658fb7df6d0c8873a/src/components/menu/nz-submenu.component.ts#L44 , but the bug still exist if remove these lines https://github.com/NG-ZORRO/ng-zorro-antd/blob/37cef47ac8c033a5dcc104a658fb7df6d0c8873a/src/components/menu/nz-submenu.component.ts#L14-L28
@trotyl @wilsoncook any idea about this?

**Comment by awmleer** [comment] 2017-11-28 06:29
我自己试着解决了一下，已经发PR了

**Comment by vthinkxie** [comment] 2018-03-17 16:52
resolved in 0.7.0

**Closed by vthinkxie** 2018-03-17 16:52 UTC
Labels: Bug
