### ISSUE TITLE
Unable to build in Production

### ISSUE THREAD

**Issue by TheAifam5** [NG-ZORRO/ng-zorro-antd#3266] opened 2019-04-13 11:28 UTC
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start?sadas](https://stackblitz.com/edit/ng-zorro-antd-start?sadas)

### Steps to reproduce
1. Create a NgModule
2. Add to that module the "NzMenuModule".
3. Build in production

### What is expected?
Should not stop the compilation and should not use typings to resolve the class, but a real .ts files.

### What is actually happening?
Unexpected value 'NzMenuModule in node_modules/ng-zorro-antd/ng-zorro-antd.d.ts' imported by the module 'ServicesModule in src/app/core/services/services.module.ts'. Please add a @NgModule annotation.

| Environment | Info |
|---|---|
| ng-zorro-antd | 7.1.0 |
| Browser | NOT RELATED |

---
Not possible to build on Stacklitz in Production mode.

**Comment by vthinkxie** [comment] 2019-04-13 14:47
https://ng.ant.design/docs/faq/en#why-individually-importing-is-not-supported

**Comment by vthinkxie** [comment] 2019-04-13 14:48
we do not support secondary module import now, plz follow https://github.com/NG-ZORRO/ng-zorro-antd/pull/3234

**Comment by wendzhue** [comment] 2019-04-14 03:30
Duplicate of #700.

**Comment by fabioemoutinho** [comment] 2019-05-20 15:29
7.4.0 reintroduces this problem @wendzhue , happened to me with NzButtonModule, with a shared module that imports and exports the NzButtonModule (among others).

> ERROR in : Unexpected value 'NzButtonModule in C:/pf/node_modules/ng-zorro-antd/ng-zorro-antd.d.ts' imported by the module 'SharedModule in C:/pf/apps/pf/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.

**Comment by vthinkxie** [comment] 2019-05-21 03:49
@fabioemoutinho we will fix it today, thanks for your report

**Comment by wendzhue** [comment] 2019-05-21 03:55
@fabioemoutinho ng-zorro-antd.metadata.json is messed up because a bug of ng-packagr: https://github.com/ng-packagr/ng-packagr/issues/594. We are fixing this. Thank you for your report.

**Closed** 2019-05-21 09:44 UTC
Labels: :bug: Bug, Component: Menu, 🖨Build
