### ISSUE TITLE
[nz-select] `nzAllowClear` opens the select box instead of clearing it when `nz-select` is inside a `nz-input-group` with `nzCompact`

### ISSUE THREAD

**Issue by tangdiying** [NG-ZORRO/ng-zorro-antd#6141] opened 2020-12-03 06:34 UTC
### Reproduction link
[https://stackblitz.com/edit/w6zudf--run?file=src/app/app.component.ts](https://stackblitz.com/edit/w6zudf--run?file=src/app/app.component.ts)

### Steps to reproduce
`nzAllowClear` opens the select box instead of clearing it when `nz-select` is inside a `nz-input-group` with `nzCompact`

### What is expected?
`nzAllowClear` clearing it instead of  opens the select box when `nz-select` is inside a `nz-input-group` with `nzCompact` 

### What is actually happening?
`nzAllowClear` opens the select box instead of clearing it when `nz-select` is inside a `nz-input-group` with `nzCompact`

| Environment | Info |
|---|---|
| ng-zorro-antd | 10.1.2 |
| Browser | everyone |

**Comment by wenqi73** [comment] 2020-12-03 06:37
Duplicate of #5989.

**Closed by wenqi73** 2020-12-03 06:37 UTC
Labels: Component: Input
