### ISSUE TITLE
When clearing the search query of select options with nzCustomContent enabled some options are empty.

### ISSUE THREAD

**Issue by kingbreddo** [NG-ZORRO/ng-zorro-antd#5178] opened 2020-04-29 09:10 UTC
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-z6h7vm](https://stackblitz.com/edit/ng-zorro-antd-start-z6h7vm)

### Steps to reproduce
 * Go to https://ng.ant.design/components/select/en#components-select-demo-custom-content
 * Go to the section about custom option template
 * Fill `Mac` as search query
 * Clear the search query

### What is expected?
It should show the Windows option with its custom content

### What is actually happening?
The option is not showing the original content before search.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.0 |
| Browser | Firefox 75.0 64Bits on MacOS |

---
I ran into this bug when creating an phone number component. After searching for the calling code it will have a list with empty content. Only after scrolling they will reappear.

The stackblitz has the same code used inside the demo. But in the stackblitz it works :/

![Screenshot 2020-04-29 at 10 47 54](https://user-images.githubusercontent.com/24498630/80579345-29929600-8a0a-11ea-95ea-be0470b8c1c2.png)

**Comment by zmzimpl** [comment] 2020-05-08 03:20
same issue here!
![image](https://user-images.githubusercontent.com/27490895/81366670-d2817500-911d-11ea-89ac-24ebc56ce787.png)

**Comment by bilalucar** [comment] 2020-06-02 12:05
Because of this problem, we did not upgrade our project to Angular 9. Hopefully it will be fixed as soon as possible.

**Comment by vthinkxie** [comment] 2020-06-15 10:03
Hi all, the bug is caused by the virtual scroll of `@angular/cdk`
the diff strategy and template cache has something wrong in this situation

**Closed** 2020-06-15 13:31 UTC
Labels: :bug: Bug, Component: Select, 🤚 Blocked By @angular/cdk
