### ISSUE TITLE
Ability to click in the entry field of a drop-down menu

### ISSUE THREAD

**Issue by j-boileau** [NG-ZORRO/ng-zorro-antd#4268] opened 2019-10-10 12:48 UTC
### Reproduction link
[https://ng-zorro-antd-start-s6vedu.stackblitz.io](https://ng-zorro-antd-start-s6vedu.stackblitz.io)

### Steps to reproduce
- Create a drop-down menu with search enabled
- Type in the search input
- Click on the inputed text to place the cursor

### What is expected?
Have the option to click in the input box of the drop-down menu with the search option activated so as not to depend exclusively on the keyboard to modify the search.

### What is actually happening?
The drop-down menu closes when clicking in the search box

| Environment | Info |
|---|---|
| ng-zorro-antd | 8.3.0 |
| Browser | Google Chrome - Version 77.0.3865.90 (Build officiel) (64 bits) |

---
我们很高兴使用您的图书馆    :D

**Comment by vthinkxie** [comment] 2019-10-10 13:04
Hi @j-boileau 
it is caused by the same reason as https://github.com/NG-ZORRO/ng-zorro-antd/issues/4259
there is a backdrop created by `@angular/cdk` to help detect the click outside event when open the dropdown, so there is no way to get text cursor worked when the dropdown opened now

**Comment by wenqi73** [comment] 2020-10-21 12:04
closed via #5925.

**Closed by wenqi73** 2020-10-21 12:04 UTC
Labels: Component: Select, 🤚 Blocked By @angular/cdk
